# Training Configuration
training:
  device: "cuda:1" 
  batch_size: 32
  depth: 2
  learning_rate: 0.0001
  num_epochs: 100
  early_stopping_patience: 5
  log_interval: 50


# Save Configuration
save:
  isSave: True
  save_fold_number: 4

# Model Architecture Parameters
model:
  max_gene_slots: 218
  max_drug_substructures: 17
  gene_layer_embedding_dim: 64
  substructure_layer_embedding_dim: 64
  cross_attn_embedding_dim: 64
  final_embedding_dim: 128
  output_dim: 1

# Data Paths
data:
  pathway_mask_path: "./input/pathway_mask.pt"
  pathway_laplacian_embeddings_path: "./input/pathway_laplacian_embeddings_4.pt"
  cross_validation_data_dir: "../0_dataset_CV_laplacian"

# System Settings
system:
  timezone: "Asia/Seoul"
  seed: 42
  pytorch_cuda_alloc_conf: "expandable_segments:True" 